

import re
from collections import Counter

import matplotlib.pyplot as plt
import networkx as nx
import pandas as pd
import plotly.express as px
import streamlit as st
from sklearn.linear_model import LinearRegression
from textblob import TextBlob
from wordcloud import STOPWORDS, WordCloud


# ======================================================
# PAGE CONFIG
# ======================================================
st.set_page_config(
    page_title="ConvoLens",
    page_icon="🔍",
    layout="wide",
    initial_sidebar_state="expanded",
)


# ======================================================
# CUSTOM CSS
# ======================================================
st.markdown(
    """
    <style>
    .block-container {
        padding-top: 2rem;
        padding-bottom: 2rem;
    }
    </style>
    """,
    unsafe_allow_html=True,
)


# ======================================================
# HELPER FUNCTIONS
# ======================================================
def metric_card(title, value, icon, color):
    st.markdown(
        f"""
        <div style="
            background: linear-gradient(135deg, {color}, #1f2937);
            padding: 20px;
            border-radius: 16px;
            color: white;
            text-align: center;
            box-shadow: 0 6px 16px rgba(0,0,0,0.2);
            margin-bottom: 10px;
        ">
            <div style="font-size: 28px;">{icon}</div>
            <div style="font-size: 14px; opacity: 0.9;">{title}</div>
            <div style="font-size: 30px; font-weight: bold;">{value}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )


EMOJI_PATTERN = re.compile(
    "["
    "\U0001F600-\U0001F64F"
    "\U0001F300-\U0001F5FF"
    "\U0001F680-\U0001F6FF"
    "\U0001F1E0-\U0001F1FF"
    "\U00002700-\U000027BF"
    "]+",
    flags=re.UNICODE,
)

CUSTOM_STOPWORDS = {
    "hai", "ka", "ki", "ke", "the", "and", "is", "are",
    "you", "your", "this", "that", "for", "with", "from",
    "media", "omitted", "message", "http", "https"
}


def parse_chat(chat_text):
    chat_text = chat_text.replace("\u202f", " ").replace("\u00a0", " ")

    pattern = r"(\d{1,2}/\d{1,2}/\d{2},\s\d{1,2}:\d{2}\s(?:AM|PM|am|pm))\s-\s"
    parts = re.split(pattern, chat_text)

    if len(parts) < 3:
        return pd.DataFrame(columns=["date", "user", "message"])

    dates, users, messages = [], [], []

    for i in range(1, len(parts), 2):
        if i + 1 >= len(parts):
            break

        date = parts[i]
        block = parts[i + 1].strip()
        split_msg = block.split(": ", 1)

        if len(split_msg) == 2:
            user = split_msg[0].strip()
            message = split_msg[1].strip()
        else:
            user = "group_notification"
            message = block

        dates.append(date)
        users.append(user)
        messages.append(message)

    df = pd.DataFrame({
        "date": dates,
        "user": users,
        "message": messages,
    })

    df["datetime"] = pd.to_datetime(
        df["date"],
        format="%m/%d/%y, %I:%M %p",
        errors="coerce",
    )

    df = df.dropna(subset=["datetime"])

    df["only_date"] = df["datetime"].dt.date
    df["month"] = df["datetime"].dt.month_name()
    df["day_name"] = df["datetime"].dt.day_name()
    df["hour"] = df["datetime"].dt.hour

    return df


def get_sentiment(text):
    polarity = TextBlob(str(text)).sentiment.polarity
    if polarity > 0.1:
        return "Positive"
    elif polarity < -0.1:
        return "Negative"
    return "Neutral"


def extract_emojis(text):
    return EMOJI_PATTERN.findall(str(text))


def build_summary_report(total_messages, total_users, total_words, media_count, link_count):
    report = f"""ConvoLens Summary Report
=======================

Total Messages : {total_messages}
Total Users    : {total_users}
Total Words    : {total_words}
Media Messages : {media_count}
Links Shared   : {link_count}

Generated by ConvoLens.
"""
    return report.encode("utf-8")


# ======================================================
# HEADER
# ======================================================
st.title("🔍 ConvoLens")
st.subheader("Advanced WhatsApp Chat Intelligence Dashboard")


# ======================================================
# FILE UPLOAD
# ======================================================
uploaded_file = st.file_uploader(
    "Upload WhatsApp Chat (.txt)",
    type=["txt"]
)

if uploaded_file is None:
    st.info("Please upload a WhatsApp chat export to begin.")
    st.stop()

chat_text = uploaded_file.read().decode("utf-8", errors="ignore")

with st.expander("📄 Preview of Chat"):
    st.text(chat_text[:3000])

with st.spinner("Parsing chat..."): 
    df = parse_chat(chat_text)

if df.empty:
    st.error("Could not parse the uploaded chat file.")
    st.stop()


# ======================================================
# SIDEBAR
# ======================================================
all_users = sorted([u for u in df["user"].unique() if u != "group_notification"])
users = ["Overall"] + all_users

with st.sidebar:
    st.markdown("## 👤 Analyst Profile")
    st.markdown("**Project:** ConvoLens")
    st.markdown("**Developer:** Ashish Raj")
    st.markdown("**Tech Stack:** Python, Streamlit, NLP, ML")
    st.markdown("---")
    st.markdown("## ⚙️ Analysis Options")
    selected_user = st.selectbox("Select User", users)
    st.markdown("---")
    st.info("Upload a WhatsApp chat and explore detailed insights.")


# ======================================================
# FILTER DATA
# ======================================================
if selected_user == "Overall":
    filtered_df = df[df["user"] != "group_notification"].copy()
else:
    filtered_df = df[df["user"] == selected_user].copy()

if filtered_df.empty:
    st.warning("No messages found for the selected user.")
    st.stop()

filtered_df["sentiment"] = filtered_df["message"].apply(get_sentiment)


# ======================================================
# METRICS
# ======================================================
total_messages = len(filtered_df)
total_users = filtered_df["user"].nunique()
total_words = filtered_df["message"].astype(str).apply(lambda x: len(x.split())).sum()
media_count = filtered_df["message"].str.contains("omitted", case=False, na=False).sum()
link_count = filtered_df["message"].str.count(r"https?://").sum()

st.markdown("## 📊 Overview Metrics")

c1, c2, c3, c4, c5 = st.columns(5)
with c1:
    metric_card("Messages", total_messages, "📩", "#2563eb")
with c2:
    metric_card("Users", total_users, "👥", "#7c3aed")
with c3:
    metric_card("Words", total_words, "📝", "#059669")
with c4:
    metric_card("Media", int(media_count), "🖼️", "#dc2626")
with c5:
    metric_card("Links", int(link_count), "🔗", "#ea580c")


# ======================================================
# PROGRESS BARS
# ======================================================
st.markdown("## 📈 Quick Insights")

sentiment_counts = filtered_df["sentiment"].value_counts()
positive_percentage = (
    sentiment_counts.get("Positive", 0) / sentiment_counts.sum() * 100
    if sentiment_counts.sum() > 0 else 0
)

media_percentage = (media_count / total_messages * 100) if total_messages else 0
link_percentage = (link_count / total_messages * 100) if total_messages else 0

st.write(f"😊 Positive Sentiment: {positive_percentage:.2f}%")
st.progress(min(positive_percentage / 100, 1.0))

st.write(f"🖼️ Media Messages: {media_percentage:.2f}%")
st.progress(min(media_percentage / 100, 1.0))

st.write(f"🔗 Link Messages: {link_percentage:.2f}%")
st.progress(min(link_percentage / 100, 1.0))


# ======================================================
# TABS
# ======================================================
tab_overview, tab_trends, tab_sentiment, tab_users, tab_data = st.tabs([
    "📊 Overview",
    "📈 Trends",
    "😊 Sentiment",
    "🏆 Users",
    "🗂️ Data",
])


# ======================================================
# OVERVIEW TAB
# ======================================================
with tab_overview:
    if selected_user == "Overall":
        st.subheader("📊 Top 10 Active Users")
        top_users = filtered_df["user"].value_counts().head(10)
        fig, ax = plt.subplots(figsize=(10, 4))
        top_users.plot(kind="bar", ax=ax)
        plt.xticks(rotation=45)
        plt.tight_layout()
        st.pyplot(fig)

    st.subheader("☁️ Word Cloud")
    text = " ".join(filtered_df["message"].astype(str))
    if text.strip():
        stop_words = set(STOPWORDS)
        stop_words.update(CUSTOM_STOPWORDS)
        wc = WordCloud(
            width=1200,
            height=500,
            background_color="white",
            stopwords=stop_words,
        ).generate(text)

        fig, ax = plt.subplots(figsize=(14, 6))
        ax.imshow(wc, interpolation="bilinear")
        ax.axis("off")
        st.pyplot(fig)

    st.subheader("😀 Top Emojis")
    all_emojis = []
    for msg in filtered_df["message"]:
        all_emojis.extend(extract_emojis(msg))

    if all_emojis:
        emoji_df = pd.DataFrame(
            Counter(all_emojis).most_common(10),
            columns=["Emoji", "Count"]
        )
        st.dataframe(emoji_df, use_container_width=True)
    else:
        st.info("No emojis found.")


# ======================================================
# TRENDS TAB
# ======================================================
with tab_trends:
    st.subheader("📈 Daily Message Trend")
    daily_messages = filtered_df.groupby("only_date").size().reset_index(name="Messages")
    fig = px.line(daily_messages, x="only_date", y="Messages")
    st.plotly_chart(fig, use_container_width=True)

    st.subheader("🔥 Activity Heatmap")
    heatmap = filtered_df.pivot_table(
        index="day_name",
        columns="hour",
        values="message",
        aggfunc="count",
        fill_value=0,
    )
    ordered_days = [
        "Monday", "Tuesday", "Wednesday", "Thursday",
        "Friday", "Saturday", "Sunday"
    ]
    heatmap = heatmap.reindex(ordered_days)
    st.dataframe(heatmap, use_container_width=True)

    st.subheader("🗓️ Monthly Message Count")
    st.bar_chart(filtered_df["month"].value_counts())

    st.subheader("🔮 Future Message Volume Prediction")
    if len(daily_messages) >= 2:
        daily_messages = daily_messages.reset_index(drop=True)
        X = daily_messages.index.values.reshape(-1, 1)
        y = daily_messages["Messages"].values

        model = LinearRegression()
        model.fit(X, y)

        future_index = [[len(daily_messages)]]
        prediction = model.predict(future_index)[0]
        st.metric("Predicted Messages for Next Day", max(0, int(prediction)))


# ======================================================
# SENTIMENT TAB
# ======================================================
with tab_sentiment:
    st.subheader("😊 Sentiment Analysis")
    st.bar_chart(sentiment_counts)


# ======================================================
# USERS TAB
# ======================================================
with tab_users:
    st.subheader("🏆 User Ranking")
    ranking = (
        filtered_df.groupby("user")
        .agg(Messages=("message", "count"),
             Words=("message", lambda x: sum(len(str(m).split()) for m in x)))
        .sort_values("Messages", ascending=False)
        .reset_index()
    )
    st.dataframe(ranking, use_container_width=True)

    if selected_user == "Overall" and len(ranking) > 1:
        st.subheader("🕸️ Interaction Network Graph")
        G = nx.Graph()
        top_users = ranking.head(10)["user"].tolist()

        for user in top_users:
            G.add_node(user)

        for i in range(len(top_users)):
            for j in range(i + 1, len(top_users)):
                G.add_edge(top_users[i], top_users[j])

        fig, ax = plt.subplots(figsize=(8, 6))
        pos = nx.spring_layout(G, seed=42)
        nx.draw(
            G,
            pos,
            with_labels=True,
            node_size=2000,
            font_size=8,
            ax=ax,
        )
        st.pyplot(fig)

    st.subheader("📏 Longest Message")
    filtered_df["char_count"] = filtered_df["message"].astype(str).str.len()
    longest = filtered_df.loc[filtered_df["char_count"].idxmax()]
    st.write(f"**User:** {longest['user']}")
    st.write(f"**Characters:** {int(longest['char_count'])}")
    st.text_area("Message", longest["message"], height=150)


# ======================================================
# DATA TAB
# ======================================================
with tab_data:
    st.subheader("📥 Download Reports")

    csv = filtered_df.to_csv(index=False).encode("utf-8")
    st.download_button(
        "⬇️ Download Processed Data (CSV)",
        data=csv,
        file_name="processed_chat_data.csv",
        mime="text/csv",
    )

    summary = build_summary_report(
        total_messages,
        total_users,
        total_words,
        int(media_count),
        int(link_count),
    )

    st.download_button(
        "📄 Download Summary Report (TXT)",
        data=summary,
        file_name="convolens_summary.txt",
        mime="text/plain",
    )

    st.subheader("🗂️ Parsed Data")
    st.dataframe(filtered_df, use_container_width=True)


# ======================================================
# FOOTER
# ======================================================
st.markdown("---")
st.markdown(
    """
    <div style='text-align:center; color:gray; padding:20px;'>
        🔍 <b>ConvoLens</b><br>
        Advanced WhatsApp Chat Intelligence Dashboard<br>
        Built with ❤️ using Python, Streamlit, NLP, and Machine Learning<br>
        © 2026 Ashish Raj
    </div>
    """,
    unsafe_allow_html=True,
)
